### ISSUE TITLE
PolyMath is not loaded when installing the project using the Metacello script 

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/edit-distances#18]
Steps to reproduce:
1. Create a new Pharo image (8, 9 or 10).
2. Run the How to install it? scrip that is available in the README.
3. You will se that PolyMath is not loaded:
![Screenshot 2021-08-05 at 14 57 51](https://user-images.githubusercontent.com/33934979/128353727-1c5ea63b-3ac2-4e1a-8ce9-3399b85fa1ee.png)

**Comment by jordanmontt** [comment]
Is this an issue of the PolyMath baseline? Or an issue of our baseline (edit-distances) @hernanmd

**Comment by hernanmd** [comment]
I tried with a Pharo 9 image, but I cannot reproduce it. PolyMath is fully loaded without problems.
Can you re-try checking the Transcript log?

![Screen Shot 2021-08-05 at 7 10 27 PM](https://user-images.githubusercontent.com/4825959/128392315-539fc4b1-dca7-4fab-9c0c-c06fa484ebaf.png)

**Comment by jordanmontt** [comment]
Yes because I already fixed it and pushed directly to master. Sorry for the bother :)
