### ISSUE TITLE
Do we need to delete the Levenshtein distance implementation in Array because it's never used and produces an exception?

### ISSUE THREAD

**Issue by bloomabir** [pharo-ai/edit-distances#29]

**Comment by jordanmontt** [comment]
Hello Hernan @hernanmd I hope that you are doing fine. We were working with Abir @bloomabir and we saw that there is two implementations of `levenshteinDistanceTo:` One is on `Array` and the other one is on `String`.

As far as we look at it, the Levenshtein distance only makes sense for characters, not for numbers. And also, we try to use the array implementation with: `#(1 2 3) levenshteinDistanceTo: #(1 2 4)` or also `#(A B C) levenshteinDistanceTo: #(A B D)` but both of them produce an exception.

So, do we delete the Array implementation? What do you think?

Thanks,
Sebastian

**Comment by hernanmd** [comment]
Hi @jordanmontt . I'm not fully clear, why Levenshtein distance could not be implemented in Array or even SequenceableCollection?

Why does it produces an exception? 

I see nothing wrong having two implementations. The fact that an additional implementation in Array or SequenceableCollection is not working does not mean that should be deleted, but fixed.
